language: node_js
node_js:
- '8'
cache: 
directories:
- node_modules
script:
- npm run lint
- npm test
- npm run build
deploy:
  api_key:
    secure: Ji6fEvUP4XMM8F7X4oX5tS8KnFFVcIt2ZFE68JQ73O+BHeHaM1QWHUVlw6MCApmNcJLjlQd3jKiKZni0bKtugbK7NWmUHbHbSuvLxjNsPcZ21AJyWCJaeSW0cICOKnCpbecWy1V04dw0qNV+gDUvv3ZTLpyJAA1NXkweIDdl5UQh0L80rjfC2PMHjiiNCXrZjxaXG0I2aFIem+OVfPjeTSSPiu1zNBGO3qRe1SV7iyrNVpySmRVt6AwumvjwzxsFg1BNiJkgMZQmbEb6q5UuGS66sfsBm5+0G4OaxQUDdRmn8MCXU+i/vDK6W5wS7FIFOQVih3tOK6zuMkAPAjUiBp0MGMkfk2odozgOLzS8W8bPgyOcaDUuI/wPoLWML191DhMT3Y7DHyQBkzWz3MuOLQ37B9Qka7bGgsBWeM8/R7hmFp3bzu5eeSu0NdP0f0KIRDjlAyCjmF4ydRMe3tG/VojH81YAkCIgq78gHG8x4uDG95NkwHMPFAsFt/9Yblbqi9jd6jPOqdQLt0kE/N2RIZrEUoZJVkUh+BzCIpSsQh7SLOco+IrhXfUUL35K+vVJtBIW+jJ5zHKFiR+RXPi6WCDrDS91hyl/C9PzdSeAJL5GacLgSMtT3jYgcxPRwPfgfyNQDbTViKT+c6saS1mnHXf8GZZVn6an9zIg/bIfkTI=
